### ISSUE TITLE
Please label 1.3.0 as broken

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/libcomcat-feedstock#36]
Hi @conda-forge/core,

Please move version *1.3.0* my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

The command line scripts we attempt to install with this version don't work.

**Comment by ocefpaf** [comment]
Done! See https://anaconda.org/conda-forge/libcomcat/files?version=1.3.0
